### ISSUE TITLE
Thumbnails won't open to larger file.

### ISSUE THREAD

**Issue by pricemtchemp** [AppStateLibrary/omeka#22] opened 2015-05-08 17:43 UTC
When you click on the thumbnail photo, the larger image won't open instead you get an exe file extension and a prompt to save.
http://omeka.library.appstate.edu/items/show/15157
http://omeka.library.appstate.edu/items/show/15121
http://omeka.library.appstate.edu/items/show/15077
http://omeka.library.appstate.edu/items/show/15058

There are several others...some in this collection open fine, with no prompting
to save.

**Comment by ksclarke** [comment] 2015-05-10 17:27
Looking into this.  These files are actually .exe files on the disk (in the original files folder on the disk).  There are 188 of them and they were all uploaded on the same day: Aug 19. 2014.

**Comment by ksclarke** [comment] 2015-05-10 23:08
After a bit of research and testing, I've discovered what's happening.  These are items that are coming in from CONTENTdm.  The "original file name" field in the Omeka record says the original file's name is: http://contentdm.library.appstate.edu:81/cgi-bin/showfile.exe (which isn't really the original file's name in CONTENTdm).

This seems to be a pretty old problem as I tracked down an old thread in the Omeka mailing list talking about it: https://groups.google.com/forum/#!searchin/omeka-dev/exe/omeka-dev/qvAniM87OME/gKPdi-slByQJ (it's from 2010/2011, but there is a reply on it as recent as 12/2014 saying it's still not fixed).

The issue is that whatever is importing from CONTENTdm isn't make use of the Content-Disposition header, which tells the name of the original file (as its coming out of CONTENTdm).  As a result, the file is coming in as the URL (with a .exe on the end).  So, Omeka thinks that's the file name and uses that, putting a file with an exe extension in the files/original directory.  When a browser requests that image, the browser doesn't recognize the .exe file as an image so tries to download it.

To clean this up, two steps are needed:
* Change the file names in the files/original directory
* Change the file names in the database itself

The first step can be handled with:

    for file in *.exe; do mv "$file" "${file%.exe}.jpg"; done

There are also two other useful commands for seeing the count of these records:

    find /home/omeka/files -name "*.exe" |grep -c .

And seeing a list of the records themselves:

    find /home/omeka/files -name "*.exe"

Of course, the above makes the assumption that all these .exe files were JPG files (which they might not be).  You could have someone confirm that in CONTENTdm manually.  I can give you a list of all the files I've fixed if you'd like it.

The second step is to clean up the database references to these files.  I wrote a little PHP script to do that:

    <?php
    //
    // A script to fix up files in the Omeka database loaded from CONTENTdm.
    //
    
    $servername = "localhost";
    $username = "";
    $password = "";
    $dbname = "";
    
    // Create and check the db connection
    $db = new mysqli($servername, $username, $password, $dbname);
    
    if ($db->connect_error) {
        die("Connection failed: " . $db->connect_error);
    }
    
    // Make sure autocommit is turned off, we want to batch everything together
    $db->autocommit(FALSE);
    
    // Run a query to find the .exe files
    $sql = <<<SQL
        SELECT filename FROM omeka_files WHERE original_filename LIKE '%showfile.exe' AND filename LIKE '%.exe'
    SQL;

    // Run a query that will update .exe filenames
    $update = <<<SQL
        UPDATE omeka_files SET filename = ? WHERE filename = ?
    SQL;

    try {
        if (!$result = $db->query($sql)) {
            throw new Exception('There was an error running the query [' . $db->error . ']');
        }

        while ($row = $result->fetch_assoc()) {
            $newName = substr($row['filename'], 0, -4) . '.jpg';
            echo $row['filename'] . ' ' . $newName . PHP_EOL;

            $statement = $db->prepare($update);
            $statement->bind_param('ss', $newName, $row['filename']);
            $statement->execute();
            $statement->free_result();
            $statement->close();
        }

        echo 'Total results: ' . $result->num_rows . PHP_EOL;

        $result->free();
    } catch (Exception $details) {
        $db->rollback();
        die($details->getMessage());
    }

    $db->close();
    ?>

To actually run that, you need to put in the username, password, and database information.

In doing this, I've found a bunch of other items that were imported from CONTENTdm without an extension at all.  I've created a different ticket for them (#24).  These may or may not be an issue.  In the one case I checked, the browser was still able to detect what type of file it was (from the header or ??)

Before closing this ticket, I was to verify with @pricemtchemp that these really were all images.

I've disabled ".exe" as an acceptable file type in Omeka to hopefully catch this problem at the point of ingest (rather than having to do a post-ingest cleanup).  I don't expect the archive is actually storing real .exe files(?)

Also probably "to be resolved" is how these images are being ingested from CONTENTdm (and whether we can do anything to solve this problem).

**Comment by ksclarke** [comment] 2015-05-31 15:01
Pam confirmed these are all images.

**Closed by ksclarke** 2015-05-31 15:01 UTC
